### ISSUE TITLE
[x]XP ([x]XP total) doesn't render and your two column doesn't render properly.

### ISSUE THREAD

**Issue by aknight2015** [ebshimizu/5e-monster-maker#115]
![Mother Madness_v1](https://github.com/ebshimizu/5e-monster-maker/assets/47067592/a8e3c2d2-bf8f-4b47-b1b3-0e839980bc1a)
Excellent webapp though.

**Comment by ebshimizu** [comment]
- ah right the [x]XP isn't really a token since you could choose to award an amount of XP that isn't equivalent to the CR of the creature. I could add tokens that let you specify the amount of XP through the CR (like [XP:4] or something)
- The width of the exported png stat block is determined by the current size of the stat block on the right. You can click and drag the center divider to control the width (it's admitted a bit of a hack but it's the easiest method at the moment).

**Comment by aknight2015** [comment]
Got it. I will manually fix the XP then.

Considering the scope of the project, yeah, easiest works. What you need to do next is do this same app, but for items, and equipment, and spells, and everything else.
