### ISSUE TITLE
website not working 

### ISSUE THREAD

**Issue by hollowhub** [ebshimizu/5e-monster-maker#60]
i was making a monster on the website and it suddenly stopped working saying how something went wrong it also gave the Error code: STATUS_BREAKPOINT. sorry if this isnt how i would tell you this i dont know how this site works

**Comment by ebshimizu** [comment]
hey! that's odd, there haven't been any changes to the live site since the change 19 days ago. I also see there's a possibly related issue in #61.

Do you remember what you were doing and whether or not the site still loads? I am able to access it through my browser so I'm unsure how to replicate this issue. If you're familiar with the web development tools, please take a screenshot of the console window (ctrl+shift+i is the keyboard shortcut to open that)

**Comment by hollowhub** [comment]
Hi so sorry for not replying for a while i was busy with some work i was in the middle of writing down some actions and it suddenly just crashed and im not familiar with dev tools but when i tried it it just told me that it was disconnected from the page again so sorry for not replying faster

**Comment by ebshimizu** [comment]
hm odd to say the least, to get the site working again you can clear your internet data (see #61). Hopefully it doesn't happen again, and if so well at least i'm working on a new version where this shouldn't happen :)

**Comment by hollowhub** [comment]
ok got it thank you
