### ISSUE TITLE
site unable to load?

### ISSUE THREAD

**Issue by Uncle0llie** [ebshimizu/5e-monster-maker#61]
was working on a monster, and when changing, if i remember correctly, legendary actions, site crashed. when reloading/restarting/etc. page keeps crashing. unsure if this is an issue on the site side or possibly with the saved file of the monster i was making.

**Comment by ebshimizu** [comment]
this is likely an issue with the saved data. If you're able to open the web dev console i could use a screenshot of whatever message is in there (ctrl+shift+i is the shortcut). To fix this you'd need to clear web browser data or i need to apply a patch to fix whatever data issue is causing this

**Comment by Uncle0llie** [comment]
from what i can see there is no message whatsoever when i open the dev console so im not sure what to do about that on my front. clearing user data has seemed to work so it seems there was some issue with the original save. however when opening the dev console again this message did pop up. not sure if this is anything out of the ordinary but ill still post it here (cant link image for some reason so ill just transcribe): Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

**Comment by ebshimizu** [comment]
Hmmm yeah those messages aren't in my browser so that's probably a local extension. Very odd that it wouldn't print an exception on load, and not sure how the legendary actions section got corrupted (I tried a few things this morning and it seemed ok).

glad that it's fixed, thanks for the report! definitely let me know if it happens again, and i'll see if i can add better global error handling for cases like this and #60
